### ISSUE TITLE
以下这段代码调用后起什么作用

### ISSUE THREAD

**Issue by wuseal** [sgwhp/openapm#2]
嗨：，请问下面截图调用完后起什么作用，最后返回NULL，好像也没有看到修改什么内容
![image](https://cloud.githubusercontent.com/assets/9211902/25340112/508d99e4-2937-11e7-82b4-483edf418cb0.png)

**Comment by sgwhp** [comment]
给ProcessBuilder加上-javaagent参数，也就是给java和dx工具的jvm设置agent

**Comment by wuseal** [comment]
谢谢，知道了，这个设置添加参数弄的比较隐藏，一下还没看出来
